services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./logs/db_logs:/var/log/postgresql
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      sh -c "
      ./wait-for-it.sh db:5432 -- alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
    volumes:
      - .:/app
      - ./logs/app_logs:/app/logs
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db

volumes:
  postgres_data:
